package com.smarte.response.data.model

import com.google.gson.annotations.SerializedName

/**
 * Response Team entity matching backend/C++ state schema.
 */
data class ResponseTeam(
    @SerializedName("id", alternate = ["teamId"]) val id: String = "",
    val type: String = "AMBULANCE",
    val status: String = "AVAILABLE", // AVAILABLE, BUSY, OFFLINE
    val nodeId: String? = null,
    val activeAssignmentId: String? = null,
    val lat: Double? = 0.0,
    @SerializedName("lon", alternate = ["lng"]) val lon: Double? = 0.0,
    val name: String? = null,
    val baseStation: String? = null
) {
    val teamId: String get() = id
    val displayName: String get() = name ?: (id + " - " + typeDisplayName)
    val station: String get() = baseStation ?: nodeId ?: "STATION"
    val isAvailable: Boolean get() = status.equals("AVAILABLE", ignoreCase = true)
    val isBusy: Boolean get() = status.equals("BUSY", ignoreCase = true)
    val isOffline: Boolean get() = status.equals("OFFLINE", ignoreCase = true)

    val typeIcon: String
        get() = when (type.uppercase()) {
            "FIRE_BRIGADE", "FIRE" -> "FIRE"
            "RESCUE_TEAM", "RESCUE" -> "RESCUE"
            else -> "AMB"
        }

    val typeDisplayName: String
        get() = when (type.uppercase()) {
            "FIRE_BRIGADE", "FIRE" -> "Fire Brigade"
            "RESCUE_TEAM", "RESCUE" -> "Rescue Team"
            else -> "Ambulance"
        }
}

/**
 * Emergency incident entity matching backend schema.
 */
data class Emergency(
    val id: String = "",
    val type: String = "MEDICAL",
    val priority: String = "HIGH", // CRITICAL, HIGH, MEDIUM, LOW
    val status: String? = null, // PENDING, ASSIGNED, COMPLETED
    val nodeId: String = "",
    val injured: Int? = 0,
    val severity: Int? = 3,
    val lat: Double? = 0.0,
    @SerializedName("lon", alternate = ["lng"]) val lon: Double? = 0.0,
    val description: String? = null
) {
    val typeIcon: String
        get() = when (type.uppercase()) {
            "FIRE" -> "FIRE"
            "MEDICAL" -> "MED"
            "FLOOD" -> "FLOOD"
            "BUILDING_COLLAPSE" -> "COLLAPSE"
            else -> "EMERGENCY"
        }
}

/**
 * Assignment entity generated by C++ DSA engine.
 */
data class Assignment(
    @SerializedName("id", alternate = ["assignmentId"]) val id: String = "",
    val emergencyId: String = "",
    val teamId: String = "",
    val status: String = "OFFERED", // OFFERED, ASSIGNED, ACCEPTED, DECLINED, COMPLETED
    @SerializedName("routeDistanceKm", alternate = ["distance"]) val routeDistanceKm: Double = 0.0,
    @SerializedName("routeNodes", alternate = ["route"]) val routeNodes: List<String> = emptyList(),
    val etaMinutes: Int = 5
) {
    val assignmentId: String get() = id
    val distance: Double get() = routeDistanceKm
    val route: List<String> get() = routeNodes
}

/**
 * City Graph Vertex.
 */
data class CityNode(
    val id: String = "",
    val name: String = "",
    val lat: Double = 0.0,
    @SerializedName("lon", alternate = ["lng"]) val lon: Double = 0.0
) {
    val lng: Double get() = lon
    val displayName: String get() = if (name.isNotBlank()) name else id
}

/**
 * City Graph Edge.
 */
data class Road(
    val id: String = "",
    val u: String = "",
    val v: String = "",
    val distanceKm: Double = 0.0,
    val status: String = "OPEN" // OPEN, BLOCKED
)

/**
 * Full state snapshot response from GET /api/state.
 */
data class SnapshotResponse(
    val success: Boolean = false,
    val cmd: String? = null,
    val teams: List<ResponseTeam>? = null,
    val emergencies: List<Emergency>? = null,
    val roads: List<Road>? = null,
    val nodes: List<CityNode>? = null,
    val assignments: List<Assignment>? = null
)

/**
 * Team-specific detail response from GET /api/teams/:id.
 */
data class TeamDetailResponse(
    val success: Boolean = false,
    val team: ResponseTeam? = null,
    val activeAssignment: Assignment? = null,
    val error: String? = null
)

/**
 * Generic command result response.
 */
data class GenericResponse(
    val success: Boolean = false,
    val cmd: String? = null,
    val error: String? = null,
    val allocatedTeamId: String? = null,
    val distanceKm: Double? = null,
    val assignmentId: String? = null,
    val emergencyId: String? = null
)

/**
 * Dynamic Reroute payload calculated by C++ Dijkstra Engine.
 */
data class RerouteData(
    val status: String? = null,
    @SerializedName("totalDistanceKm", alternate = ["newDistance"]) val totalDistanceKm: Double = 0.0,
    @SerializedName("nodeIds", alternate = ["newRoute"]) val nodeIds: List<String> = emptyList(),
    @SerializedName("etaMinutes", alternate = ["newEta"]) val etaMinutes: Int = 5
) {
    val newRoute: List<String> get() = nodeIds
    val newDistance: Double get() = totalDistanceKm
    val newEta: Int get() = etaMinutes
}

/**
 * WebSocket broadcast payload schema.
 */
data class WebSocketEvent(
    val type: String? = null,
    val eventType: String? = null,
    val emergencyId: String? = null,
    val teamId: String? = null,
    val assignmentId: String? = null,
    val roadId: String? = null,
    val status: String? = null,
    val nodeId: String? = null,
    val allocatedTeamId: String? = null,
    val reroute: RerouteData? = null,
    val data: SnapshotResponse? = null
)

enum class ConnectionStatus {
    CONNECTED,
    CONNECTING,
    OFFLINE
}
